### ISSUE TITLE
[1.12] Incompatible with Waypoints crazy error

### ISSUE THREAD

**Issue by MokahTGS** [blay09/NetherPortalFix#11]
Getting a bad problem when using the Waypoints mod and this mod together.

Console log: https://pastebin.com/4acKZGLw

What's happening is that using the Waypoint between the nether and the overworld lands me not on the overworld waypoint but in some other part of the overworld.  I don't know what mod is doing this but this mod is in the log.  Also all of my Jouneymap waypoints and mapped areas are gone.

This is the waypoint mod where I will also post an issue: https://github.com/kamildanak/Waypoints/issues

**Comment by BlayTheNinth** [comment]
Can you try if the problem still occurs with this version? 
http://jenkins.blay09.net/job/NetherPortalFix%201.12/7/

**Comment by BlayTheNinth** [comment]
Released the fix on Curse now. It should fix this issue, if not, let me know.
