### ISSUE TITLE
netherportalfix-1.9-3.0.3 crashes dedicated forge server 1.9 build 1809 on startup

### ISSUE THREAD

**Issue by kreezxil** [blay09/NetherPortalFix#2]
Issue: netherportalfix-1.9-3.0.3 crashes dedicated forge server 1.9 build 1809 on startup

crash report:
https://gist.github.com/7e8bd32dfa0205ee2cb1

fml server latest:
https://gist.github.com/29c4f2db5f88b5baf49d

**Comment by BlayTheNinth** [comment]
Fixed in latest version.
