### ISSUE TITLE
Mod breaks "back through the portal" protection

### ISSUE THREAD

**Issue by Sadumon** [blay09/NetherPortalFix#22]
Using vanilla mechanics, if you teleport through a Nether portal (either way), you will not teleport back through the portal unless you step out of the portal and back in it.  You will still get the visual effects, but you will never teleport back.

Something in NetherPortalFix seems to break that protection, depending on which block of the portal I enter/exit through.  I have a 2 wide by 3 tall portal in the overworld, stretching E-W.  If I teleport from the eastern portal block into the nether, step out and teleport back into the OW, I will teleport back to the nether if I don't move.  If I teleport through the western block of my portal in the OW, and then teleport back through the Nether portal, I have the protection and won't teleport back.

This seems to be worse when multiple OW portals are linked to a single Nether portal.  I think this is because the protection from re-teleporting is linked only to the block you would come out using vanilla mechanics, so in the case where this fix is moving you to a different portal altogether, there are no blocks you can enter that won't result in you doing the loop.

Sometimes this can result in an endless loop of teleporting back and forth if I just stand still, depending on which blocks I teleported through most recently.

On clients that have a bit more lag when changing dimensions, this can sometimes result in the player teleporting back before they get a chance to complete loading the new dimension, putting them in an endless loop.

Also, on the server logs, I can see warnings that the players going through the portals are moving too quickly.  It looks like players are entering the world near the global spawn point, and then being immediately moved to the proper location.  We think this may be causing extra lag on the client side because, depending on how quickly that movement is sent, it can cause players to try to load the terrain from the spawn and then from their targeted nether portal (which exacerbates the previous issue of looping back to the Nether).

**Comment by naqaden** [comment]
Sadumon, in which version(s) of NPF do you experience this?

**Comment by Sadumon** [comment]
5.3.13, which appears to be the latest version.

**Comment by Sadumon** [comment]
5.3.13, which appears to be the latest version.

**Comment by BlayTheNinth** [comment]
I can't seem to reproduce this, are you using Sponge or anything else that could mess with portals?

**Comment by BlayTheNinth** [comment]
I think I just had it reproduced on myself while playing on 1.15.2 - due to lagspikes whenever a player changed dimensions, I ended up being unable to leave the portal before being warped back, resulting in an infinite portal loop.

**Comment by BlayTheNinth** [comment]
Possible fix for 1.15+ is now available on CurseForge, we'll see if that works.
