### ISSUE TITLE
Entities such as animals and villagers are invisible after returning through a Portal

### ISSUE THREAD

**Issue by demfels** [blay09/NetherPortalFix#26]
I am pretty sure this started when the last version 1.12.1-5.3.12 was released.  I am not 100% certain it is this mod, but thus far it is my best guess based on my experimentation.  When you go through a portal and then return, all the animals are invisible.  I can hear them, but not see them.

I am using the Fantasy Evolved II pack: https://minecraft.curseforge.com/projects/fantasy-evolved-ii

**Comment by demfels** [comment]
Here is video: https://youtu.be/6hcu7kUqpFs

**Comment by BlayTheNinth** [comment]
NetherPortalFix only affects vanilla's nether portals, not portals from other mods, so this is more likely to be an issue in the Hunting Dimension mod itself.
