### ISSUE TITLE
Use ITeleporter

### ISSUE THREAD

**Issue by LatvianModder** [blay09/NetherPortalFix#28]
https://github.com/blay09/NetherPortalFix/blob/1.12/src/main/java/net/blay09/mods/netherportalfix/NetherPortalFix.java#L145-L195

These methods are old, Forge has added ITeleporter and fixed issues with cross-dimension teleportation when using `entity.changeDimension(int dimension, ITeleporter);` You can see https://github.com/LatvianModder/FTBLib/blob/master/src/main/java/com/feed_the_beast/ftblib/lib/math/TeleporterDimPos.java#L81 for example. Just came here after I got reported an issue with this mod and old methods may be the cause. (https://github.com/LatvianModder/FTBUtilities/issues/577#issuecomment-440283753)

**Comment by BlayTheNinth** [comment]
Fixed in 1.14+ by using the new ServerPlayerEntity.teleport() method.
