### ISSUE TITLE
1.16.1 - I'm still coming out at other people's portals

### ISSUE THREAD

**Issue by lulabyte** [blay09/NetherPortalFix#38]
Have the mod installed client and server side and we're still coming out of each other's nether portals.

Thanks for your work!

**Comment by mike1000195** [comment]
can confirm over here too. came here to see if the issue was posted already. 1.16.1

**Comment by BlayTheNinth** [comment]
I can't seem to reproduce this issue, does this happen with only NetherPortalFix installed? Is there anything in the logs?

**Comment by mike1000195** [comment]
im not sure, i am updating to 1.16.3 here soon, im just waiting on like one or two mods to update. i havent tried to see if its happening in 1.16.3 also yet, but the issue that was happening was primarily on a hosted server between friends. 

the issue that i had narrowed down was that when somebody else was over 4000+ block away in the overworld, and they went into the nether via a fresh overworld portal, it wouldn't spawn a new portal in the nether. it would already use the pre-existing portal that i had already made over 4000 block away in the overworld. that is the issue thats happening

**Comment by BlayTheNinth** [comment]
NetherPortalFix doesn't change nether portal spawning behaviour, it will only remember what portals a player came from and will forcibly return them to that portal when they go back instead of the first portal within range.

**Comment by mike1000195** [comment]
oh i see, it must be some other mod i have conflicting with it somehow then, ill check around
