### ISSUE TITLE
[1.15.2] Not a only server-side mod

### ISSUE THREAD

**Issue by Intezium** [blay09/NetherPortalFix#39]
Forge-31.2.41
NetherPortalFix-6.0.2
![](https://user-images.githubusercontent.com/20191322/94384652-c8ebbe80-014b-11eb-967c-4388b17f0691.png)

**Comment by BlayTheNinth** [comment]
Does this prevent joining the server or is it only visual?

**Comment by Intezium** [comment]
> **Does this prevent joining the server** or is it only visual?

**Comment by Intezium** [comment]
Oh, sorry, another mod did not allow you to connect to the server and I thought that there is the same problem.. 


> Does this prevent joining the server or is it **only visual**?

**Comment by mike1000195** [comment]
Blay, im glad you marked it as a bug, it did this in previous versions too so i had to install it on client side for everyone also to keep people from freaking out and wondering why they were having "mod conflictions" when trying to join. it still worked perfectly fine, but the visual false-positive error is definitely something that could be looked at
