### ISSUE TITLE
Nether portals in the overworld link with portals above y=128 in the Nether

### ISSUE THREAD

**Issue by BinuwaraN2** [blay09/NetherPortalFix#40]
This issue was fixed in v1.15. However, can you add this to Minecraft v1.12.2?

**Comment by BlayTheNinth** [comment]
Is this a bug in NetherPortalFix or a Vanilla bug you're asking to be fixed by NetherPortalFix?

1.12 is no longer supported, so unless this is some serious gamebreaking bug in NetherPortalFix itself there won't be any further updates for Minecraft 1.12.
