### ISSUE TITLE
When I enter a nether portal I can no longer get into my server

### ISSUE THREAD

**Issue by Lich23** [blay09/NetherPortalFix#41]
I'm not 100% sure it's this mod but this is what the server logs say when I try to log in: https://pastebin.com/6JnjzJn2

**Comment by BlayTheNinth** [comment]
Looks like an interaction between FTB Ranks and Just Enough Resources resulting in a client-only class to be loaded:

```
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[...]
at jeresources.profiling.ProfileCommand.lambda$register$0(ProfileCommand.java:26)
at dev.ftb.mods.ftbranks.impl.RankCommandPredicate.lambda$test$0(RankCommandPredicate.java:41)
```

**Comment by Lich23** [comment]
Thank you for your answer but I found the solution a while ago. Operators cannot go throught nether portal it seems. The issue is surely deeper than that but I don't wanna do anymore digging.
