### ISSUE TITLE
Duplicate Portals

### ISSUE THREAD

**Issue by piebaker** [blay09/NetherPortalFix#54]
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Fabric

### Mod Loader Version

Quilt 0.17.8

### Mod Version

10.0.0

### Describe the Issue

Duplicate portals are appearing randomly when passing through nether portals. It appears to be that a return portal is not found, so a new one is generated, however it then redirects the user to the correct already existing return portal. This is hard to reproduce, but evident, as 3 portals have spawned within ~10 blocks of each other. Addtionally a user entered a portal from the nether and had a new return portal generate far from the correct overworld portal it is connected to. Possibly due to that user never having entered that portal from either side?
This mod is loaded serverside only. 

### Logs

Will be provided on request, as issue is not in current log to unpredictability 

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Quilt loader, with a full gamut of server enhancements. Can provide list on request

**Comment by Sephiroth91** [comment]
With the last version of the mod I got this error at Minecraft 1.18.2.
