### ISSUE TITLE
Duplicate Portals

### ISSUE THREAD

**Issue by Sephiroth91** [blay09/NetherPortalFix#55]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

Forge 40.2.0

### Mod Version

9.0.1

### Describe the Issue

If I leave the nether, every time a new portal is creating in the vicinity of the portal I used to enter the nether. We are playing on a minecraft server and the  error is up to every player.

**Comment by BlayTheNinth** [comment]
Did your server start out fresh on the 9.0.1 version or did it run an ealier version before?

**Comment by Sephiroth91** [comment]
After a few hours of research i found out that the bug comes from the performance mod canary. The mod breaks the nether portal link. https://github.com/AbdElAziz333/Canary/issues/98
