### ISSUE TITLE
Portal teleports player to broken portal

### ISSUE THREAD

**Issue by Xarton7** [blay09/NetherPortalFix#59]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.14.14

### Mod Version

1.0.0

### Balm Version

4.5.7

### Describe the Issue

After I removed a portal, the other one still teleports me to the broken portal
Please fix it
Special thanks to the mod creators 

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium

**Comment by BlayTheNinth** [comment]
Duplicate of #58
