### ISSUE TITLE
[1.11.x-4.3.1] putting people in lava on Forge 13.20.0.2315

### ISSUE THREAD

**Issue by kreezxil** [blay09/NetherPortalFix#6]
See this thread for more details: https://minecraft.curseforge.com/projects/colonial-expansion?comment=120

**Comment by BlayTheNinth** [comment]
The latest beta versions for 1.11.2 and 1.12 should fix this issue. If you try it out, please let me know if it keeps throwing you in lava or break in other ways.

**Comment by FiveEYZ** [comment]
Gonna describe whats happening:

I made a portal (cord: x16, y71, z98) and traveled just fine to the nether (cord: x5, y66, z9) the first time, when I traveled back to overworld I was sent to a location (cord: x6, y66, z9) bit away from the first portal.

Then I told a friend to test the portal, same thing happen to him, when he got back I was unable to see him and when I went to the location he landed then I got teleported (dont know if this is true, or if it just takes time to teleport me) to the real nether portal.

So I decided to travel to the nether a second time, and now im able to see my friend (that is currently in the overworld) and im unable to go thru the portal again.

using:
- NetherPortalFix_1.12-5.3.4
- spongeforge-1.12-2397-7.0.0-BETA-2486

and hope u understand what im trying to say, its a mess :)

**Comment by FiveEYZ** [comment]
I also have NetherEx that seem to contain some sort of "PortalFix" (just saw it when I went thru it's config)

**Comment by BlayTheNinth** [comment]
That sounds very odd. I feel it might be another SpongeForge interaction, so I'll see if similar issues arise on regular Forge before spending lots of time debugging.

NetherEx does implement the old NetherPortalFix implementation in their mod, though it's disabled automatically when NetherPortalFix is installed.
