### ISSUE TITLE
Modrinth release for 1.20.6 doesn't show correct dependencies

### ISSUE THREAD

**Issue by NotAFlyingGoose** [blay09/NetherPortalFix#61]
### Minecraft Version

1.20.6

### Mod Loader

Forge

### Mod Loader Version

Fabric-1.20.6

### Mod Version

16.0.1

### Balm Version

N/A

### Describe the Issue

I'm not sure if this applies to curseforge, I'm programming an automated tool that has to download mods + their dependencies off modrinth.

Unfortunately while the [modrinth release for 1.20.6](https://modrinth.com/mod/netherportalfix/version/16.0.1+fabric-1.20.6) correctly marks the fabric api as a dependency, it doesn't show balm, which it has done for [other releases](https://modrinth.com/mod/netherportalfix/version/14.0.3+fabric-1.20.2)

This seems like an oversight, just letting you guys know 😁

**Comment by BlayTheNinth** [comment]
Should all be fixed now.
