### ISSUE TITLE
Feature / Idea

### ISSUE THREAD

**Issue by Silka64** [blay09/NetherPortalFix#62]
First, thanks for the mod and 1.20.6 !

I would like a feature called something like "PerfectlyRespectNetherRatio" 1:8
we could also name the feature : pixel-perfect-nether-portal-link+teleoport

So, if i have many portal nears me in nether, and they are strictly linked (perfect match), so i can use them to teleport between world in a perfect way. Sry for my bad english

**Comment by BlayTheNinth** [comment]
As far as I know that is already Vanilla behaviour. NetherPortalFix only remembers and returns you to where you entered each individual portal from, so it should not conflict with that. A completely new and separate mechanic would be out of scope for this mod.
