### ISSUE TITLE
Doesn't work with Arclight

### ISSUE THREAD

**Issue by marcellonovak** [blay09/NetherPortalFix#64]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

1.19.2 Forge 43.4.0

### Mod Version

1.19-10.0.1

### Balm Version

1.19.2-4.6.0

### Describe the Issue

Running this all on an arclight server (for plugins), and the linkage is broken, go in through portal A, pop out at B, go back in, pop out at C, and going back through C/B just loops me. I've tried breaking and replacing all portals.

Strange thing is, it works in single player, so maybe it's not compatible with arclight? I'm not sure, but something's amiss. I'm using Arclight 1.19.2-1.0.5

### Logs

https://pastebin.com/B79FCERZ

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Embeddium, but it works in single player?

**Comment by BlayTheNinth** [comment]
Custom server distributions are not supported in general. If the issue only occurs when using those, you will have to report the issue to them.
