### ISSUE TITLE
No return portal found

### ISSUE THREAD

**Issue by niqeisw** [blay09/NetherPortalFix#65]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

lates

### Mod Version

21.0.1

### Balm Version

21.0.6

### Describe the Issue

Hello, I encountered a problem on the server. The Nether Portal Fix mod is flooding the console with repetitive messages, and the only solution is restarting, which doesn’t always help.
![image](https://github.com/user-attachments/assets/a1fc3d03-d88f-405b-bd49-68f0aa823816)

**Comment by BlayTheNinth** [comment]
This was already fixed in 21.0.2
