### ISSUE TITLE
[1.10.2] Portal's still behave as vanilla

### ISSUE THREAD

**Issue by themechman** [blay09/NetherPortalFix#9]
Good day!

Unfortunately I am running into vanilla portal behavior for a plain forge server using the latest version.

MC: 1.10.2
Forge: 12.18.3.2185

**Comment by BlayTheNinth** [comment]
Try v3.3.5, it uses a new implementation that should be more stable than the old one.

**Comment by themechman** [comment]
Thanks. Will let you know.
